config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "gardens#index"
  resources :gardens do
    resources :plants
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
  validates :name, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, presence: true
  validates :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController

  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plants = Plant.all
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def show
    @plant = Plant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<% @gardens.each do |garden| %>
  <%= link_to garden.name, garden_path(garden) %>
<% end %>

app/views/gardens/show.html.erb
<div style='border: 2px solid red; padding: 2rem 3rem;margin-bottom:5rem ;'>
  <%= @garden.name %>
</div>


<% @plants.each do |plant| %>
  <div style='color: purple;'>
    <%= link_to plant.name, garden_plant_path(plant) %>
  </div>

  <img src="
    <% plant.image_url %>
  " alt="">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/show.html.erb
<%= @plant.name %>
<%= @plant.image_url %>